format = """
[ ](bg:#FFB088)[ ](bg:#FF8B5C)[ ](bg:#FF7845)\
[ ](bg:#FF6B35 fg:#ffffff)\
$shell\
[ ](bg:#006680 fg:#FF6B35)\
$directory\
[ ](fg:#006680 bg:#0f2428)\
$git_branch\
$git_status\
[ ](fg:#0f2428 bg:#0a1a1d)\
$nodejs\
$rust\
$golang\
$python\
[ ](fg:#0a1a1d bg:#1a3a41)\
$time\
[ ](fg:#1a3a41)\
\n$character"""

[shell]
bash_indicator = "[ BASH ](bg:#FF6B35 fg:#ffffff)"
zsh_indicator = "[󰏰 ZSH ](bg:#FF6B35 fg:#ffffff)"
fish_indicator = "[󰈺 FISH ](bg:#FF6B35 fg:#ffffff)"
unknown_indicator = "[ ?? ](bg:#FF6B35 fg:#ffffff)"
format = "$indicator"
disabled = false
[directory]
style = "fg:#ffffff bg:#006680"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
[directory.substitutions]
"Documents" = "󰈙 Documents"
"Downloads" = "󰇚 Downloads"
"Music" = "󰝚 Music"
"Pictures" = "  Pictures"
"Videos" = "󰕧 Videos"
"Projects" = "  Projects"
"GitHub" = "󰊤 GitHub"
".config" = "  .config"
"Desktop" = "󰟀 Desktop"
[git_branch]
symbol = " "
style = "bg:#0f2428"
format = '[[ $symbol $branch ](fg:#00aad4 bg:#0f2428)]($style)'
[git_status]
style = "bg:#0f2428"
format = '[[($all_status$ahead_behind )](fg:#00aad4 bg:#0f2428)]($style)'
[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bg:#0f2428"
[nodejs]
symbol = "󰎙 "
style = "bg:#0a1a1d"
format = '[[ $symbol ($version) ](fg:#00aad4 bg:#0a1a1d)]($style)'
[rust]
symbol = " "
style = "bg:#0a1a1d"
format = '[[ $symbol ($version) ](fg:#00aad4 bg:#0a1a1d)]($style)'
[golang]
symbol = "󰟓 "
style = "bg:#0a1a1d"
format = '[[ $symbol ($version) ](fg:#00aad4 bg:#0a1a1d)]($style)'
[python]
symbol = "󰌠 "
style = "bg:#0a1a1d"
format = '[[ $symbol ($version) ](fg:#00aad4 bg:#0a1a1d)]($style)'
[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1a3a41"
format = '[[   $time ](fg:#ffffff bg:#1a3a41)]($style)'
[character]
success_symbol = "[❯](#00C896)"
error_symbol = "[✗](#E74C3C)"
vimcmd_symbol = "[❮](#00C896)"
